name: Build Images and Deploy to Personal Registry

on:
  push:
    branches: [master]

concurrency:
  group: build-images
  cancel-in-progress: true

env:
  REGISTRY: mckrava
  IMAGE_TAG: 6.1.1-0.9.13-0.1.3

jobs:
  build-testnet-multiarch-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug

      - name: Download Basilisk-node
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GH_TOKEN}}
          # Required, workflow file name or ID
          workflow: tests.yml
          # Optional, will use specified workflow run
          run_id: 1705436387
          name: basilisk
          # Optional, defaults to current repo
          repo: galacticcouncil/Basilisk-node
          path: testnet

      - name: Login to my Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          file: ./testnet/testnet.Dockerfile
          tags: ${{ env.REGISTRY }}/polkadot-basilisk-testnet-multiarch:${{env.IMAGE_TAG}}
